# For all available configuration settings, please go to:
#   https://docs.viktor.ai/docs/create-apps/references/viktor-config-toml

app_type = 'tree'
# assets_path = 'assets'
# packages = []
python_version = '3.11'
# welcome_text = 'welcome.md'
